### PR TITLE
antidebug, antivm and persistance updates

### PR DESCRIPTION
**Pull request by KiExitDispatcher**
# Description

Added cool features.

## Type of change
- Triage Detection (https://tria.ge/)
- Disable Factory Reset
- ProcessProtection (CriticalProcess)
- Disable TaskManager
- Disable Registry
- Can you remove skuld? yeah easily, even if its enabled these lol all you gotta do is delete the file (in windows/protect) and there go to the file sh and type attrib -h -s and it shows the file and you delete it

### CODE REVIEW

**Review by KiExitDispatcher — COMMENTED** [review]
add critical process

**Review by KiExitDispatcher — COMMENTED** [review]
critcal process code

**Comment by hackirby** [comment]
Thank's for this PR !

I think the code looks good. I'll make some changes to clean it up before accepting the PR. However, please don't refer to this as skuld v2; it's just a set of features. skuld v2 is a project I'll work on when I have more time (I'm currently very busy).

The features you implemented will help skuld persist on the computer: removing skuld will be more challenging. Therefore, please update the README.md with new instructions for uninstalling skuld.

(I'm really busy, but I'll take care of it if you'd really prefer not to)

**Comment by KiExitDispatcher** [comment]
```bat
@echo off
title skuld remover
cd C:\Users\%USERNAME%\AppData\Roaming\Microsoft\Protect
attrib -h -s
start "" "C:\Users\%USERNAME%\AppData\Roaming\Microsoft\Protect"
ECHO PLEASE REMOVE ANY .EXE FILES THAT YOU DONT RECONGIZE!
pause
```
It disables reg stuff so next step:

### UnHook Registry (unhookreg.inf -> creds to Symantec):
```inf
[Version]

Signature=”$Chicago$”

Provider=Symantec

[DefaultInstall]

AddReg=UnhookRegKey

[UnhookRegKey]

HKLM, Software\CLASSES\batfile\shell\open\command,,,”””%1″” %*”

HKLM, Software\CLASSES\comfile\shell\open\command,,,”””%1″” %*”

HKLM, Software\CLASSES\exefile\shell\open\command,,,”””%1″” %*”

HKLM, Software\CLASSES\piffile\shell\open\command,,,”””%1″” %*”

HKLM, Software\CLASSES\regfile\shell\open\command,,,”regedit.exe “”%1″””

HKLM, Software\CLASSES\scrfile\shell\open\command,,,”””%1″” %*”

HKCU, Software\Microsoft\Windows\CurrentVersion\Policies\System,DisableRegistryTools,0x00000020,0Step
```
after, this fixed application issues from unhooking.
``` 
[Version]
Signature="$Chicago$"
Provider=Codepulze

[DefaultInstall]
AddReg=UnhookRegKey

[UnhookRegKey]
HKLM, Software\Classes\exefile\shell\open\command,,,"%1 %*"
```

### renable factory reset:
```bat
reagentc.exe /enable
```

**Comment by KiExitDispatcher** [comment]
readme updated

**Comment by KiExitDispatcher** [comment]
antidebug updated

**Comment by KiExitDispatcher** [comment]
if you dont want to rely on the code please use : https://github.com/EvilBytecode/GoDefender

**Pull request closed without merging**
